### ISSUE TITLE
direct sparse convolution in gpu mode

### ISSUE THREAD

**Issue by knsong** [IntelLabs/SkimCaffe#16]
hi， thank you for the work first. But I notice that in gpu mode, `BaseConvolutionLayer` in  `skimcaffe` uses `cusparseScsrmm()`  to perform `im2col+gemm` like convolution and treats `weights` and `col_buff` as a dense, sparse matrix respectively. I'm confused here and shouldn't it be the  inverse case that `weights` is sparse and `col_buff` is dense?

**Comment by jspark1105** [comment]
Thanks for your interest in our project. Unfortunately, we focused on CPU speedups and GPU code is not maintained. The GPU code path is mostly a remnant of Wei's https://github.com/wenwei202/caffe that we forked from. If you're interested in getting speedups in GPU from structured sparsity, please refer to that project.

**Comment by knsong** [comment]
Thank you for the reply. BTW, is there an efficient sparse winograd inference implementation in `SkimCaffe`? I noticed that `WinogradLayer<Dtype>::Forward_cpu()`  didn't take advantage of sparsity.

**Comment by jspark1105** [comment]
Sorry, looks like I didn't add the optimized sparse sparse Winograd forward implementation before I left Intel.

**Comment by knsong** [comment]
@jspark1105 Ok, thanks.
